"""``make questions`` — print the seven business questions with their current answers.

Regenerating ``docs/business_questions.md`` by hand is how documented numbers drift
away from the warehouse. Running this after a build prints the current answers, and
``--markdown`` rewrites the document from them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from medchain.config import load_config
from medchain.gold import business_questions as bq
from medchain.utils.logging import setup_logging


def _markdown_table(pdf, max_rows: int = 6) -> str:
    """Render a pandas frame as a markdown table without pulling in tabulate."""
    columns = list(pdf.columns)
    rows = ["| " + " | ".join(columns) + " |", "|" + "|".join(["---"] * len(columns)) + "|"]
    for _, record in pdf.head(max_rows).iterrows():
        cells = []
        for column in columns:
            value = record[column]
            if value is None:
                cells.append("")
            elif isinstance(value, float):
                cells.append(f"{value:,.2f}".rstrip("0").rstrip("."))
            elif isinstance(value, int):
                cells.append(f"{value:,}")
            else:
                cells.append(str(value))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def main(argv: list[str] | None = None) -> int:
    setup_logging("WARNING")
    parser = argparse.ArgumentParser(description="Answer the seven business questions")
    parser.add_argument("--env", default=None)
    parser.add_argument("--only", type=int, default=None, help="Run a single question, 1-7")
    parser.add_argument(
        "--markdown", action="store_true", help="Rewrite docs/business_questions.md"
    )
    parser.add_argument("--rows", type=int, default=6, help="Rows to show per question")
    args = parser.parse_args(argv)

    cfg = load_config(args.env)

    from medchain.spark import get_spark

    spark = get_spark(cfg)
    try:
        bq.register_views(spark, cfg)
        questions = [q for q in bq.QUESTIONS if args.only is None or q.number == args.only]

        if args.markdown:
            sections = [
                "# The Seven Business Questions\n",
                "Generated by `make questions --markdown` from the built warehouse, so the "
                "numbers here are the warehouse's current answers rather than a transcription "
                "of an earlier run.\n",
                "---\n",
            ]
            for question in questions:
                pdf = spark.sql(question.sql).limit(args.rows).toPandas()
                sections.extend([
                    f"## BQ{question.number} — {question.audience}\n",
                    f"> **{question.question}**\n",
                    "### Result\n",
                    _markdown_table(pdf, args.rows) + "\n",
                    "### Interpretation\n",
                    question.interpretation + "\n",
                    "<details>\n<summary>SQL</summary>\n",
                    "```sql",
                    question.sql.strip(),
                    "```\n</details>\n",
                    "---\n",
                ])
            target = Path(__file__).resolve().parents[3] / "docs" / "business_questions.md"
            target.write_text("\n".join(sections))
            print(f"Wrote {target}")
            return 0

        for question in questions:
            print("=" * 92)
            print(f"BQ{question.number} — {question.audience}")
            print("=" * 92)
            print(question.question)
            print()
            spark.sql(question.sql).show(args.rows, truncate=False)
            print(f"→ {question.interpretation}\n")
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    sys.exit(main())
